#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_ARCH="aarch64-darwin"

if system_profiler SPHardwareDataType | grep -q "MacBook"; then
    echo "${YELLOW}Using laptop configuration...${NC}"
    SYSTEM_TYPE="${SYSTEM_ARCH}@laptop"
else
    echo "${YELLOW}Using desktop configuration...${NC}"
    SYSTEM_TYPE="${SYSTEM_ARCH}@desktop"
fi

FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting build for ${FLAKE_SYSTEM}...${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@

echo "${YELLOW}Switching to new generation...${NC}"
./result/sw/bin/darwin-rebuild switch --flake .#${SYSTEM_TYPE} $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
